### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Hrushikesh-github** [qubvel-org/segmentation_models.pytorch#904]
```
>>> from segmentation_models_pytorch import utils
Segmentation fault (core dumped)
```
Getting segmentation fault, I have enough memory. 
I have tried this for different versions of pytorch
```
torch                        2.2.1+cu121
torchaudio                   2.2.1+rocm5.7
torchvision                  0.17.1+cu121
```
And 
```
torch                        2.2.2
torchaudio                   2.2.2
torchvision                  0.17.2
```
But none work. Cuda version is as follows:
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0```
```
But surprisingly in another system of colleague's the library is working fine.
The only change is in cuda version. 

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```
And the libraries are of same set torch==2.2.1+cu121
python version is also different, mine is Python 3.11.0rc1.

**Comment by qubvel** [comment]
Hi @Hrushikesh-github,

Thats error is common for some mismatch of cuda/cudnn/torch/torchvision versions and is not related to the library itself. Please consider debugging the environment package versions.

**Comment by Hrushikesh-github** [comment]
I used a docker image and that worked well. Initially I thought it was an error from library as other torch code was working expected but looks like it is indeed a compatibility issue.

**Comment by qubvel** [comment]
Thank you for the update!
