### ISSUE TITLE
add UperNet model 

### ISSUE THREAD

**Issue by jawi289o** [qubvel-org/segmentation_models.pytorch#906]
kindly add UperNet model

**Comment by GrantorShadow** [comment]
commenting to be a part of the discussion

**Comment by qubvel** [comment]
Hi! Thanks for the interest! Would anyone like to add this model? I will appreciate any contribution, just let me know if you are interested and need any guidance 🙂

**Comment by GrantorShadow** [comment]
I would love to this on

**Comment by qubvel** [comment]
Thanks for your interest @GrantorShadow!

You fork the repo, clone it, and copy-paste the Unet model folder in `decoders/` and modify it to `Upernet`. I suppose this will be the easiest way to adopt a new model. You have to rewrite `decoder.py` file, while `model.py` most probably will be similar or with minor changes.
Then you can open a PR for initial review and feedback.

In terms of testing would be nice to fine-tune it with an example notebook in the repo to check if the model is trainable and add some basic tests under `/tests` folder.

If you will face any particular difficulties we can discuss it here or under the PR!
Looking forward to collaborating with you, thanks!

**Comment by jawi289o** [comment]
@GrantorShadow Hi are you working on it?

**Comment by GrantorShadow** [comment]
Yes sorry I got a little delayed but will be getting it done in the next 2 weeks

**Comment by yurithefury** [comment]
Given Hugging Face integration, I believe you can simply use `UperNetForSemanticSegmentation` from `transformers`: 

```
from transformers import UperNetForSemanticSegmentation
self.model = UperNetForSemanticSegmentation.from_pretrained(
    pretrained_model_name_or_path='openmmlab/upernet-convnext-small'
    )
```
