### ISSUE TITLE
Guidance required to add CBAM Module

### ISSUE THREAD

**Issue by jawi289o** [qubvel-org/segmentation_models.pytorch#908]
Can you please guide how can I add the CBAM module in UNet and Deeplabv3p?

![cbam](https://github.com/user-attachments/assets/8d0b1071-7667-4c2f-82a7-fdd1fa1f55fd)

**Comment by qubvel** [comment]
Hi @jawi289o there is a similar attention module SCSE
https://github.com/qubvel-org/segmentation_models.pytorch/blob/c68fc942408f7ead3fd64e866204980b05a6bfb0/segmentation_models_pytorch/base/modules.py#L117-L129

So, you can just specify `decoder_attention_type="scse"`
