### ISSUE TITLE
How to predict a specified image

### ISSUE THREAD

**Issue by wangluoWSG** [qubvel-org/segmentation_models.pytorch#931]
How to use the previously trained model weights to predict a specified image and output the predicted mask.

**Comment by qubvel** [comment]
Hi @wangluoWSG, thanks for the question!

Here is an example https://github.com/qubvel-org/segmentation_models.pytorch/blob/main/examples/binary_segmentation_intro.ipynb

Please look at the end to see how to make predict and visualise the result

**Comment by wangluoWSG** [comment]
Thank you  very much！
