### ISSUE TITLE
Add Segformer model

### ISSUE THREAD

**Issue by brianhou0208** [qubvel-org/segmentation_models.pytorch#941]
## Description

There is already a Segformer encoder [mix_transformer](https://github.com/qubvel-org/segmentation_models.pytorch/blob/main/segmentation_models_pytorch/encoders/mix_transformer.py) in this repo, and the decoder architecture of Segformer is simple and similar to UPerNet. 

## Question
Is there a need to add a Segformer to this repo?, I can contribute a PR.

## Architecture
![image](https://github.com/user-attachments/assets/cbd5d4df-1363-42a0-b751-85a92813de10)

## Reference

- [official repo](https://github.com/NVlabs/SegFormer)
- [paper](https://arxiv.org/abs/2105.15203)

**Comment by qubvel** [comment]
Hi @brianhou0208, there was a demand for this architecture and it can be a great feature, especially in case we will be able to load the original weights too!

**Comment by brianhou0208** [comment]
Check the PR here : #944

**Comment by alex-stenger** [comment]
Waiting for the PR to be accepted, is there for now a way to make a SegFormer with smp, and to load weights ?
