### ISSUE TITLE
F1 score metric delivering a wrong value?

### ISSUE THREAD

**Issue by kirillmeisser** [qubvel-org/segmentation_models.pytorch#953]
Hi everyone,

I am currently having an issue with a binary segmentation problem where I get a much higher F1-Score than it actually is. I have tried calculating the F1 metric by hand using the `fn, fp, tn and tp` values from the `get_stats` method and I get a different result than the score from the `f1_score` method. I use a batch size of one and for an image i get the following results:

![image](https://github.com/user-attachments/assets/023f3a78-a53c-4778-be76-5a9b49370e53)

The code I use is the one below

```
output = torch.argmax(output, dim=1, keepdim=True)
y = y.unsqueeze(1)

tp, fp, fn, tn = smp.metrics.get_stats(output, y, mode='multiclass', num_classes=config['num_classes'] + 1)

iou_score = smp.metrics.iou_score(tp, fp, fn, tn, reduction='micro') # reduction micro would be the standard mIoU
f1_score = smp.metrics.f1_score(tp, fp, fn, tn, reduction='micro')
accuracy = smp.metrics.accuracy(tp, fp, fn, tn, reduction='micro')
recall = smp.metrics.sensitivity(tp, fp, fn, tn, reduction='micro') # a.k.a recall
precision = smp.metrics.positive_predictive_value(tp, fp, fn, tn, reduction='micro') # a.k.a precision
```

When we use the shown `fn, fp, tn and tp` values and calculate the F1 score by hand we get 810676/(810676 + 0.5*(3100+37990)) = 0.975 for the class 0 and 202/(202 + 0.5*(37990 + 3100)) = 0.0097 for the class 1. This makes an average of 0.493 and not 0.9518 as the `f1_score` states. Could someone please clarify the difference? Am I doing something wrong? By visualizing the prediction masks visually a score of 0.493 would explain the bad segmentations much better than the 0.9518. I also have a very bad DiceLoss so I do not get why the F1 score is so high. Any help would be greatly appreciated.

Best,

Kirill

**Comment by qubvel** [comment]
Hi, did you tried with different reduction?  `micro` reduction is class agnostic, it sums all tp/fp/fn/tn among classes and images and then compute f1 score. In your case probably "macro" reduction would fit better.

**Comment by kirillmeisser** [comment]
Hi @qubvel,

First of all thanks for the amazing repo and the quick response! In this problem I have a very strong class imbalance where class 1 is much rarer than the background class 0. Reading through your documentation I've seen that you recommend using `micro-imagewise` reduction in such cases and discouraged using `macro` reduction. I tried using `micro-imagewise` and I got very similar (probably the same) results as with `micro`.

Now I have tried `macro`and got the expected F1-score that reflects the performance, thank you very much! Would you say that you would generally recommend to use `macro`?

**Comment by qubvel** [comment]
Hi @kirillmeisser! I would say that the correct metric depends on your "business" task, I usually monitor several additional granular metrics besides the main one. For example, per-class f1, tp, fp, fn, tn + global f1 micro/macro as a main one. You may also have sensitivity and specificity for "1 vs all" to handle class imbalance.

**Comment by kirillmeisser** [comment]
Ah yes true thank you for the tip! Given the tp, fp, fn and tn one can effectively build any metric type. I appreciate your help and I will close the issue :)
