### ISSUE TITLE
Vanilla-fy DeepLabv3(+)

### ISSUE THREAD

**Issue by DimitrisMantas** [qubvel-org/segmentation_models.pytorch#955]
I noticed that the DeepLab ASPP has a hardcoded 50% dropout layer at the exit. I'm not sure whether this is mentioned in the original papers, but I think it should be exposed to the user.

**Comment by qubvel** [comment]
Hi @DimitrisMantas! Thanks for the issue! I would appreciate this feature if you have the bandwidth to contribute 🤗
