### ISSUE TITLE
Mention NVIDIA non-commercial in top LICENSE section

### ISSUE THREAD

**Issue by junkoda** [qubvel-org/segmentation_models.pytorch#997]
Could you mention NVIDIA license, which is written in encoders/mix_transformer.py, in the top LICENSE section?

This can cause a problem for commercial use including Kaggle, in which the competition rule often requires commercial use. I misunderstood that segFormer had become completely MIT.

For example, mmcv has a LICENSES page, which lists files with NVIDIA license.
https://github.com/open-mmlab/mmcv/blob/main/LICENSES.md

Thanks for developing and maintaining this great library! I am using a lot for Kaggle.

**Comment by qubvel** [comment]
Hi @junkoda! Thanks for opening issue! Sure, that's should be listed, would you like to make a PR?
